const allLanguages = [
  {
    '1': 'ab',
    '2': 'abk',
    '3': 'abk',
    name: 'Abkhaz',
    local: 'Аҧсуа',
    '2T': 'abk',
    '2B': 'abk',
  },
  {
    '1': 'aa',
    '2': 'aar',
    '3': 'aar',
    name: 'Afar',
    local: 'Afaraf',
    '2T': 'aar',
    '2B': 'aar',
  },
  {
    '1': 'af',
    '2': 'afr',
    '3': 'afr',
    name: 'Afrikaans',
    local: 'Afrikaans',
    '2T': 'afr',
    '2B': 'afr',
  },
  {
    '1': 'ak',
    '2': 'aka',
    '3': 'aka',
    name: 'Akan',
    local: 'Akan',
    '2T': 'aka',
    '2B': 'aka',
  },
  {
    '1': 'sq',
    '2': 'sqi',
    '3': 'sqi',
    name: 'Albanian',
    local: 'Shqip',
    '2T': 'sqi',
    '2B': 'alb',
  },
  {
    '1': 'am',
    '2': 'amh',
    '3': 'amh',
    name: 'Amharic',
    local: 'አማርኛ',
    '2T': 'amh',
    '2B': 'amh',
  },
  {
    '1': 'ar',
    '2': 'ara',
    '3': 'ara',
    name: 'Arabic',
    local: 'العربية',
    '2T': 'ara',
    '2B': 'ara',
  },
  {
    '1': 'an',
    '2': 'arg',
    '3': 'arg',
    name: 'Aragonese',
    local: 'Aragonés',
    '2T': 'arg',
    '2B': 'arg',
  },
  {
    '1': 'hy',
    '2': 'hye',
    '3': 'hye',
    name: 'Armenian',
    local: 'Հայերեն',
    '2T': 'hye',
    '2B': 'arm',
  },
  {
    '1': 'as',
    '2': 'asm',
    '3': 'asm',
    name: 'Assamese',
    local: 'অসমীয়া',
    '2T': 'asm',
    '2B': 'asm',
  },
  {
    '1': 'av',
    '2': 'ava',
    '3': 'ava',
    name: 'Avaric',
    local: 'Авар',
    '2T': 'ava',
    '2B': 'ava',
  },
  {
    '1': 'ae',
    '2': 'ave',
    '3': 'ave',
    name: 'Avestan',
    local: 'avesta',
    '2T': 'ave',
    '2B': 'ave',
  },
  {
    '1': 'ay',
    '2': 'aym',
    '3': 'aym',
    name: 'Aymara',
    local: 'Aymar',
    '2T': 'aym',
    '2B': 'aym',
  },
  {
    '1': 'az',
    '2': 'aze',
    '3': 'aze',
    name: 'Azerbaijani',
    local: 'Azərbaycanca',
    '2T': 'aze',
    '2B': 'aze',
  },
  {
    '1': 'bm',
    '2': 'bam',
    '3': 'bam',
    name: 'Bambara',
    local: 'Bamanankan',
    '2T': 'bam',
    '2B': 'bam',
  },
  {
    '1': 'ba',
    '2': 'bak',
    '3': 'bak',
    name: 'Bashkir',
    local: 'Башҡортса',
    '2T': 'bak',
    '2B': 'bak',
  },
  {
    '1': 'eu',
    '2': 'eus',
    '3': 'eus',
    name: 'Basque',
    local: 'Euskara',
    '2T': 'eus',
    '2B': 'baq',
  },
  {
    '1': 'be',
    '2': 'bel',
    '3': 'bel',
    name: 'Belarusian',
    local: 'Беларуская',
    '2T': 'bel',
    '2B': 'bel',
  },
  {
    '1': 'bn',
    '2': 'ben',
    '3': 'ben',
    name: 'Bengali',
    local: 'বাংলা',
    '2T': 'ben',
    '2B': 'ben',
  },
  {
    '1': 'bh',
    '2': 'bih',
    '3': 'bih',
    name: 'Bihari',
    local: 'भोजपुरी',
    '2T': 'bih',
    '2B': 'bih',
  },
  {
    '1': 'bi',
    '2': 'bis',
    '3': 'bis',
    name: 'Bislama',
    local: 'Bislama',
    '2T': 'bis',
    '2B': 'bis',
  },
  {
    '1': 'bs',
    '2': 'bos',
    '3': 'bos',
    name: 'Bosnian',
    local: 'Bosanski',
    '2T': 'bos',
    '2B': 'bos',
  },
  {
    '1': 'br',
    '2': 'bre',
    '3': 'bre',
    name: 'Breton',
    local: 'Brezhoneg',
    '2T': 'bre',
    '2B': 'bre',
  },
  {
    '1': 'bg',
    '2': 'bul',
    '3': 'bul',
    name: 'Bulgarian',
    local: 'Български',
    '2T': 'bul',
    '2B': 'bul',
  },
  {
    '1': 'my',
    '2': 'mya',
    '3': 'mya',
    name: 'Burmese',
    local: 'မြန်မာဘာသာ',
    '2T': 'mya',
    '2B': 'bur',
  },
  {
    '1': 'ca',
    '2': 'cat',
    '3': 'cat',
    name: 'Catalan',
    local: 'Català',
    '2T': 'cat',
    '2B': 'cat',
  },
  {
    '1': 'ch',
    '2': 'cha',
    '3': 'cha',
    name: 'Chamorro',
    local: 'Chamoru',
    '2T': 'cha',
    '2B': 'cha',
  },
  {
    '1': 'ce',
    '2': 'che',
    '3': 'che',
    name: 'Chechen',
    local: 'Нохчийн',
    '2T': 'che',
    '2B': 'che',
  },
  {
    '1': 'ny',
    '2': 'nya',
    '3': 'nya',
    name: 'Chichewa',
    local: 'Chichewa',
    '2T': 'nya',
    '2B': 'nya',
  },
  {
    '1': 'zh',
    '2': 'zho',
    '3': 'zho',
    name: 'Chinese',
    local: '中文',
    '2T': 'zho',
    '2B': 'chi',
  },
  {
    '1': 'cv',
    '2': 'chv',
    '3': 'chv',
    name: 'Chuvash',
    local: 'Чӑвашла',
    '2T': 'chv',
    '2B': 'chv',
  },
  {
    '1': 'kw',
    '2': 'cor',
    '3': 'cor',
    name: 'Cornish',
    local: 'Kernewek',
    '2T': 'cor',
    '2B': 'cor',
  },
  {
    '1': 'co',
    '2': 'cos',
    '3': 'cos',
    name: 'Corsican',
    local: 'Corsu',
    '2T': 'cos',
    '2B': 'cos',
  },
  {
    '1': 'cr',
    '2': 'cre',
    '3': 'cre',
    name: 'Cree',
    local: 'ᓀᐦᐃᔭᐍᐏᐣ',
    '2T': 'cre',
    '2B': 'cre',
  },
  {
    '1': 'hr',
    '2': 'hrv',
    '3': 'hrv',
    name: 'Croatian',
    local: 'Hrvatski',
    '2T': 'hrv',
    '2B': 'hrv',
  },
  {
    '1': 'cs',
    '2': 'ces',
    '3': 'ces',
    name: 'Czech',
    local: 'Čeština',
    '2T': 'ces',
    '2B': 'cze',
  },
  {
    '1': 'da',
    '2': 'dan',
    '3': 'dan',
    name: 'Danish',
    local: 'Dansk',
    '2T': 'dan',
    '2B': 'dan',
  },
  {
    '1': 'dv',
    '2': 'div',
    '3': 'div',
    name: 'Divehi',
    local: 'Divehi',
    '2T': 'div',
    '2B': 'div',
  },
  {
    '1': 'nl',
    '2': 'nld',
    '3': 'nld',
    name: 'Dutch',
    local: 'Nederlands',
    '2T': 'nld',
    '2B': 'dut',
  },
  {
    '1': 'dz',
    '2': 'dzo',
    '3': 'dzo',
    name: 'Dzongkha',
    local: 'རྫོང་ཁ',
    '2T': 'dzo',
    '2B': 'dzo',
  },
  {
    '1': 'en',
    '2': 'eng',
    '3': 'eng',
    name: 'English',
    local: 'English',
    '2T': 'eng',
    '2B': 'eng',
  },
  {
    '1': 'eo',
    '2': 'epo',
    '3': 'epo',
    name: 'Esperanto',
    local: 'Esperanto',
    '2T': 'epo',
    '2B': 'epo',
  },
  {
    '1': 'et',
    '2': 'est',
    '3': 'est',
    name: 'Estonian',
    local: 'Eesti',
    '2T': 'est',
    '2B': 'est',
  },
  {
    '1': 'ee',
    '2': 'ewe',
    '3': 'ewe',
    name: 'Ewe',
    local: 'Eʋegbe',
    '2T': 'ewe',
    '2B': 'ewe',
  },
  {
    '1': 'fo',
    '2': 'fao',
    '3': 'fao',
    name: 'Faroese',
    local: 'Føroyskt',
    '2T': 'fao',
    '2B': 'fao',
  },
  {
    '1': 'fj',
    '2': 'fij',
    '3': 'fij',
    name: 'Fijian',
    local: 'Na Vosa Vaka-Viti',
    '2T': 'fij',
    '2B': 'fij',
  },
  {
    '1': 'fi',
    '2': 'fin',
    '3': 'fin',
    name: 'Finnish',
    local: 'Suomi',
    '2T': 'fin',
    '2B': 'fin',
  },
  {
    '1': 'fr',
    '2': 'fra',
    '3': 'fra',
    name: 'French',
    local: 'Français',
    '2T': 'fra',
    '2B': 'fre',
  },
  {
    '1': 'ff',
    '2': 'ful',
    '3': 'ful',
    name: 'Fula',
    local: 'Fulfulde',
    '2T': 'ful',
    '2B': 'ful',
  },
  {
    '1': 'gl',
    '2': 'glg',
    '3': 'glg',
    name: 'Galician',
    local: 'Galego',
    '2T': 'glg',
    '2B': 'glg',
  },
  {
    '1': 'ka',
    '2': 'kat',
    '3': 'kat',
    name: 'Georgian',
    local: 'ქართული',
    '2T': 'kat',
    '2B': 'geo',
  },
  {
    '1': 'de',
    '2': 'deu',
    '3': 'deu',
    name: 'German',
    local: 'Deutsch',
    '2T': 'deu',
    '2B': 'ger',
  },
  {
    '1': 'el',
    '2': 'ell',
    '3': 'ell',
    name: 'Greek',
    local: 'Ελληνικά',
    '2T': 'ell',
    '2B': 'gre',
  },
  {
    '1': 'gn',
    '2': 'grn',
    '3': 'grn',
    name: 'Guaraní',
    local: "Avañe'ẽ",
    '2T': 'grn',
    '2B': 'grn',
  },
  {
    '1': 'gu',
    '2': 'guj',
    '3': 'guj',
    name: 'Gujarati',
    local: 'ગુજરાતી',
    '2T': 'guj',
    '2B': 'guj',
  },
  {
    '1': 'ht',
    '2': 'hat',
    '3': 'hat',
    name: 'Haitian',
    local: 'Kreyòl Ayisyen',
    '2T': 'hat',
    '2B': 'hat',
  },
  {
    '1': 'ha',
    '2': 'hau',
    '3': 'hau',
    name: 'Hausa',
    local: 'هَوُسَ',
    '2T': 'hau',
    '2B': 'hau',
  },
  {
    '1': 'he',
    '2': 'heb',
    '3': 'heb',
    name: 'Hebrew',
    local: 'עברית',
    '2T': 'heb',
    '2B': 'heb',
  },
  {
    '1': 'hz',
    '2': 'her',
    '3': 'her',
    name: 'Herero',
    local: 'Otjiherero',
    '2T': 'her',
    '2B': 'her',
  },
  {
    '1': 'hi',
    '2': 'hin',
    '3': 'hin',
    name: 'Hindi',
    local: 'हिन्दी',
    '2T': 'hin',
    '2B': 'hin',
  },
  {
    '1': 'ho',
    '2': 'hmo',
    '3': 'hmo',
    name: 'Hiri Motu',
    local: 'Hiri Motu',
    '2T': 'hmo',
    '2B': 'hmo',
  },
  {
    '1': 'hu',
    '2': 'hun',
    '3': 'hun',
    name: 'Hungarian',
    local: 'Magyar',
    '2T': 'hun',
    '2B': 'hun',
  },
  {
    '1': 'ia',
    '2': 'ina',
    '3': 'ina',
    name: 'Interlingua',
    local: 'Interlingua',
    '2T': 'ina',
    '2B': 'ina',
  },
  {
    '1': 'id',
    '2': 'ind',
    '3': 'ind',
    name: 'Indonesian',
    local: 'Bahasa Indonesia',
    '2T': 'ind',
    '2B': 'ind',
  },
  {
    '1': 'ie',
    '2': 'ile',
    '3': 'ile',
    name: 'Interlingue',
    local: 'Interlingue',
    '2T': 'ile',
    '2B': 'ile',
  },
  {
    '1': 'ga',
    '2': 'gle',
    '3': 'gle',
    name: 'Irish',
    local: 'Gaeilge',
    '2T': 'gle',
    '2B': 'gle',
  },
  {
    '1': 'ig',
    '2': 'ibo',
    '3': 'ibo',
    name: 'Igbo',
    local: 'Igbo',
    '2T': 'ibo',
    '2B': 'ibo',
  },
  {
    '1': 'ik',
    '2': 'ipk',
    '3': 'ipk',
    name: 'Inupiaq',
    local: 'Iñupiak',
    '2T': 'ipk',
    '2B': 'ipk',
  },
  {
    '1': 'io',
    '2': 'ido',
    '3': 'ido',
    name: 'Ido',
    local: 'Ido',
    '2T': 'ido',
    '2B': 'ido',
  },
  {
    '1': 'is',
    '2': 'isl',
    '3': 'isl',
    name: 'Icelandic',
    local: 'Íslenska',
    '2T': 'isl',
    '2B': 'ice',
  },
  {
    '1': 'it',
    '2': 'ita',
    '3': 'ita',
    name: 'Italian',
    local: 'Italiano',
    '2T': 'ita',
    '2B': 'ita',
  },
  {
    '1': 'iu',
    '2': 'iku',
    '3': 'iku',
    name: 'Inuktitut',
    local: 'ᐃᓄᒃᑎᑐᑦ',
    '2T': 'iku',
    '2B': 'iku',
  },
  {
    '1': 'ja',
    '2': 'jpn',
    '3': 'jpn',
    name: 'Japanese',
    local: '日本語',
    '2T': 'jpn',
    '2B': 'jpn',
  },
  {
    '1': 'jv',
    '2': 'jav',
    '3': 'jav',
    name: 'Javanese',
    local: 'Basa Jawa',
    '2T': 'jav',
    '2B': 'jav',
  },
  {
    '1': 'kl',
    '2': 'kal',
    '3': 'kal',
    name: 'Kalaallisut',
    local: 'Kalaallisut',
    '2T': 'kal',
    '2B': 'kal',
  },
  {
    '1': 'kn',
    '2': 'kan',
    '3': 'kan',
    name: 'Kannada',
    local: 'ಕನ್ನಡ',
    '2T': 'kan',
    '2B': 'kan',
  },
  {
    '1': 'kr',
    '2': 'kau',
    '3': 'kau',
    name: 'Kanuri',
    local: 'Kanuri',
    '2T': 'kau',
    '2B': 'kau',
  },
  {
    '1': 'ks',
    '2': 'kas',
    '3': 'kas',
    name: 'Kashmiri',
    local: 'كشميري',
    '2T': 'kas',
    '2B': 'kas',
  },
  {
    '1': 'kk',
    '2': 'kaz',
    '3': 'kaz',
    name: 'Kazakh',
    local: 'Қазақша',
    '2T': 'kaz',
    '2B': 'kaz',
  },
  {
    '1': 'km',
    '2': 'khm',
    '3': 'khm',
    name: 'Khmer',
    local: 'ភាសាខ្មែរ',
    '2T': 'khm',
    '2B': 'khm',
  },
  {
    '1': 'ki',
    '2': 'kik',
    '3': 'kik',
    name: 'Kikuyu',
    local: 'Gĩkũyũ',
    '2T': 'kik',
    '2B': 'kik',
  },
  {
    '1': 'rw',
    '2': 'kin',
    '3': 'kin',
    name: 'Kinyarwanda',
    local: 'Kinyarwanda',
    '2T': 'kin',
    '2B': 'kin',
  },
  {
    '1': 'ky',
    '2': 'kir',
    '3': 'kir',
    name: 'Kyrgyz',
    local: 'Кыргызча',
    '2T': 'kir',
    '2B': 'kir',
  },
  {
    '1': 'kv',
    '2': 'kom',
    '3': 'kom',
    name: 'Komi',
    local: 'Коми',
    '2T': 'kom',
    '2B': 'kom',
  },
  {
    '1': 'kg',
    '2': 'kon',
    '3': 'kon',
    name: 'Kongo',
    local: 'Kongo',
    '2T': 'kon',
    '2B': 'kon',
  },
  {
    '1': 'ko',
    '2': 'kor',
    '3': 'kor',
    name: 'Korean',
    local: '한국어',
    '2T': 'kor',
    '2B': 'kor',
  },
  {
    '1': 'ku',
    '2': 'kur',
    '3': 'kur',
    name: 'Kurdish',
    local: 'Kurdî',
    '2T': 'kur',
    '2B': 'kur',
  },
  {
    '1': 'kj',
    '2': 'kua',
    '3': 'kua',
    name: 'Kwanyama',
    local: 'Kuanyama',
    '2T': 'kua',
    '2B': 'kua',
  },
  {
    '1': 'la',
    '2': 'lat',
    '3': 'lat',
    name: 'Latin',
    local: 'Latina',
    '2T': 'lat',
    '2B': 'lat',
  },
  {
    '1': 'lb',
    '2': 'ltz',
    '3': 'ltz',
    name: 'Luxembourgish',
    local: 'Lëtzebuergesch',
    '2T': 'ltz',
    '2B': 'ltz',
  },
  {
    '1': 'lg',
    '2': 'lug',
    '3': 'lug',
    name: 'Ganda',
    local: 'Luganda',
    '2T': 'lug',
    '2B': 'lug',
  },
  {
    '1': 'li',
    '2': 'lim',
    '3': 'lim',
    name: 'Limburgish',
    local: 'Limburgs',
    '2T': 'lim',
    '2B': 'lim',
  },
  {
    '1': 'ln',
    '2': 'lin',
    '3': 'lin',
    name: 'Lingala',
    local: 'Lingála',
    '2T': 'lin',
    '2B': 'lin',
  },
  {
    '1': 'lo',
    '2': 'lao',
    '3': 'lao',
    name: 'Lao',
    local: 'ພາສາລາວ',
    '2T': 'lao',
    '2B': 'lao',
  },
  {
    '1': 'lt',
    '2': 'lit',
    '3': 'lit',
    name: 'Lithuanian',
    local: 'Lietuvių',
    '2T': 'lit',
    '2B': 'lit',
  },
  {
    '1': 'lu',
    '2': 'lub',
    '3': 'lub',
    name: 'Luba-Katanga',
    local: 'Tshiluba',
    '2T': 'lub',
    '2B': 'lub',
  },
  {
    '1': 'lv',
    '2': 'lav',
    '3': 'lav',
    name: 'Latvian',
    local: 'Latviešu',
    '2T': 'lav',
    '2B': 'lav',
  },
  {
    '1': 'gv',
    '2': 'glv',
    '3': 'glv',
    name: 'Manx',
    local: 'Gaelg',
    '2T': 'glv',
    '2B': 'glv',
  },
  {
    '1': 'mk',
    '2': 'mkd',
    '3': 'mkd',
    name: 'Macedonian',
    local: 'Македонски',
    '2T': 'mkd',
    '2B': 'mac',
  },
  {
    '1': 'mg',
    '2': 'mlg',
    '3': 'mlg',
    name: 'Malagasy',
    local: 'Malagasy',
    '2T': 'mlg',
    '2B': 'mlg',
  },
  {
    '1': 'ms',
    '2': 'msa',
    '3': 'msa',
    name: 'Malay',
    local: 'Bahasa Melayu',
    '2T': 'msa',
    '2B': 'may',
  },
  {
    '1': 'ml',
    '2': 'mal',
    '3': 'mal',
    name: 'Malayalam',
    local: 'മലയാളം',
    '2T': 'mal',
    '2B': 'mal',
  },
  {
    '1': 'mt',
    '2': 'mlt',
    '3': 'mlt',
    name: 'Maltese',
    local: 'Malti',
    '2T': 'mlt',
    '2B': 'mlt',
  },
  {
    '1': 'mi',
    '2': 'mri',
    '3': 'mri',
    name: 'Māori',
    local: 'Māori',
    '2T': 'mri',
    '2B': 'mao',
  },
  {
    '1': 'mr',
    '2': 'mar',
    '3': 'mar',
    name: 'Marathi',
    local: 'मराठी',
    '2T': 'mar',
    '2B': 'mar',
  },
  {
    '1': 'mh',
    '2': 'mah',
    '3': 'mah',
    name: 'Marshallese',
    local: 'Kajin M̧ajeļ',
    '2T': 'mah',
    '2B': 'mah',
  },
  {
    '1': 'mn',
    '2': 'mon',
    '3': 'mon',
    name: 'Mongolian',
    local: 'Монгол',
    '2T': 'mon',
    '2B': 'mon',
  },
  {
    '1': 'na',
    '2': 'nau',
    '3': 'nau',
    name: 'Nauru',
    local: 'Dorerin Naoero',
    '2T': 'nau',
    '2B': 'nau',
  },
  {
    '1': 'nv',
    '2': 'nav',
    '3': 'nav',
    name: 'Navajo',
    local: 'Diné Bizaad',
    '2T': 'nav',
    '2B': 'nav',
  },
  {
    '1': 'nd',
    '2': 'nde',
    '3': 'nde',
    name: 'Northern Ndebele',
    local: 'isiNdebele',
    '2T': 'nde',
    '2B': 'nde',
  },
  {
    '1': 'ne',
    '2': 'nep',
    '3': 'nep',
    name: 'Nepali',
    local: 'नेपाली',
    '2T': 'nep',
    '2B': 'nep',
  },
  {
    '1': 'ng',
    '2': 'ndo',
    '3': 'ndo',
    name: 'Ndonga',
    local: 'Owambo',
    '2T': 'ndo',
    '2B': 'ndo',
  },
  {
    '1': 'nb',
    '2': 'nob',
    '3': 'nob',
    name: 'Norwegian Bokmål',
    local: 'Norsk (Bokmål)',
    '2T': 'nob',
    '2B': 'nob',
  },
  {
    '1': 'nn',
    '2': 'nno',
    '3': 'nno',
    name: 'Norwegian Nynorsk',
    local: 'Norsk (Nynorsk)',
    '2T': 'nno',
    '2B': 'nno',
  },
  {
    '1': 'no',
    '2': 'nor',
    '3': 'nor',
    name: 'Norwegian',
    local: 'Norsk',
    '2T': 'nor',
    '2B': 'nor',
  },
  {
    '1': 'ii',
    '2': 'iii',
    '3': 'iii',
    name: 'Nuosu',
    local: 'ꆈꌠ꒿ Nuosuhxop',
    '2T': 'iii',
    '2B': 'iii',
  },
  {
    '1': 'nr',
    '2': 'nbl',
    '3': 'nbl',
    name: 'Southern Ndebele',
    local: 'isiNdebele',
    '2T': 'nbl',
    '2B': 'nbl',
  },
  {
    '1': 'oc',
    '2': 'oci',
    '3': 'oci',
    name: 'Occitan',
    local: 'Occitan',
    '2T': 'oci',
    '2B': 'oci',
  },
  {
    '1': 'oj',
    '2': 'oji',
    '3': 'oji',
    name: 'Ojibwe',
    local: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    '2T': 'oji',
    '2B': 'oji',
  },
  {
    '1': 'cu',
    '2': 'chu',
    '3': 'chu',
    name: 'Old Church Slavonic',
    local: 'Словѣ́ньскъ',
    '2T': 'chu',
    '2B': 'chu',
  },
  {
    '1': 'om',
    '2': 'orm',
    '3': 'orm',
    name: 'Oromo',
    local: 'Afaan Oromoo',
    '2T': 'orm',
    '2B': 'orm',
  },
  {
    '1': 'or',
    '2': 'ori',
    '3': 'ori',
    name: 'Oriya',
    local: 'ଓଡି଼ଆ',
    '2T': 'ori',
    '2B': 'ori',
  },
  {
    '1': 'os',
    '2': 'oss',
    '3': 'oss',
    name: 'Ossetian',
    local: 'Ирон æвзаг',
    '2T': 'oss',
    '2B': 'oss',
  },
  {
    '1': 'pa',
    '2': 'pan',
    '3': 'pan',
    name: 'Panjabi',
    local: 'ਪੰਜਾਬੀ',
    '2T': 'pan',
    '2B': 'pan',
  },
  {
    '1': 'pi',
    '2': 'pli',
    '3': 'pli',
    name: 'Pāli',
    local: 'पाऴि',
    '2T': 'pli',
    '2B': 'pli',
  },
  {
    '1': 'fa',
    '2': 'fas',
    '3': 'fas',
    name: 'Persian',
    local: 'فارسی',
    '2T': 'fas',
    '2B': 'per',
  },
  {
    '1': 'pl',
    '2': 'pol',
    '3': 'pol',
    name: 'Polish',
    local: 'Polski',
    '2T': 'pol',
    '2B': 'pol',
  },
  {
    '1': 'ps',
    '2': 'pus',
    '3': 'pus',
    name: 'Pashto',
    local: 'پښتو',
    '2T': 'pus',
    '2B': 'pus',
  },
  {
    '1': 'pt',
    '2': 'por',
    '3': 'por',
    name: 'Portuguese',
    local: 'Português',
    '2T': 'por',
    '2B': 'por',
  },
  {
    '1': 'qu',
    '2': 'que',
    '3': 'que',
    name: 'Quechua',
    local: 'Runa Simi',
    '2T': 'que',
    '2B': 'que',
  },
  {
    '1': 'rm',
    '2': 'roh',
    '3': 'roh',
    name: 'Romansh',
    local: 'Rumantsch',
    '2T': 'roh',
    '2B': 'roh',
  },
  {
    '1': 'rn',
    '2': 'run',
    '3': 'run',
    name: 'Kirundi',
    local: 'Kirundi',
    '2T': 'run',
    '2B': 'run',
  },
  {
    '1': 'ro',
    '2': 'ron',
    '3': 'ron',
    name: 'Romanian',
    local: 'Română',
    '2T': 'ron',
    '2B': 'rum',
  },
  {
    '1': 'ru',
    '2': 'rus',
    '3': 'rus',
    name: 'Russian',
    local: 'Русский',
    '2T': 'rus',
    '2B': 'rus',
  },
  {
    '1': 'sa',
    '2': 'san',
    '3': 'san',
    name: 'Sanskrit',
    local: 'संस्कृतम्',
    '2T': 'san',
    '2B': 'san',
  },
  {
    '1': 'sc',
    '2': 'srd',
    '3': 'srd',
    name: 'Sardinian',
    local: 'Sardu',
    '2T': 'srd',
    '2B': 'srd',
  },
  {
    '1': 'sd',
    '2': 'snd',
    '3': 'snd',
    name: 'Sindhi',
    local: 'سنڌي‎',
    '2T': 'snd',
    '2B': 'snd',
  },
  {
    '1': 'se',
    '2': 'sme',
    '3': 'sme',
    name: 'Northern Sami',
    local: 'Sámegiella',
    '2T': 'sme',
    '2B': 'sme',
  },
  {
    '1': 'sm',
    '2': 'smo',
    '3': 'smo',
    name: 'Samoan',
    local: 'Gagana Sāmoa',
    '2T': 'smo',
    '2B': 'smo',
  },
  {
    '1': 'sg',
    '2': 'sag',
    '3': 'sag',
    name: 'Sango',
    local: 'Sängö',
    '2T': 'sag',
    '2B': 'sag',
  },
  {
    '1': 'sr',
    '2': 'srp',
    '3': 'srp',
    name: 'Serbian',
    local: 'Српски',
    '2T': 'srp',
    '2B': 'srp',
  },
  {
    '1': 'gd',
    '2': 'gla',
    '3': 'gla',
    name: 'Gaelic',
    local: 'Gàidhlig',
    '2T': 'gla',
    '2B': 'gla',
  },
  {
    '1': 'sn',
    '2': 'sna',
    '3': 'sna',
    name: 'Shona',
    local: 'ChiShona',
    '2T': 'sna',
    '2B': 'sna',
  },
  {
    '1': 'si',
    '2': 'sin',
    '3': 'sin',
    name: 'Sinhala',
    local: 'සිංහල',
    '2T': 'sin',
    '2B': 'sin',
  },
  {
    '1': 'sk',
    '2': 'slk',
    '3': 'slk',
    name: 'Slovak',
    local: 'Slovenčina',
    '2T': 'slk',
    '2B': 'slo',
  },
  {
    '1': 'sl',
    '2': 'slv',
    '3': 'slv',
    name: 'Slovene',
    local: 'Slovenščina',
    '2T': 'slv',
    '2B': 'slv',
  },
  {
    '1': 'so',
    '2': 'som',
    '3': 'som',
    name: 'Somali',
    local: 'Soomaaliga',
    '2T': 'som',
    '2B': 'som',
  },
  {
    '1': 'st',
    '2': 'sot',
    '3': 'sot',
    name: 'Southern Sotho',
    local: 'Sesotho',
    '2T': 'sot',
    '2B': 'sot',
  },
  {
    '1': 'es',
    '2': 'spa',
    '3': 'spa',
    name: 'Spanish',
    local: 'Español',
    '2T': 'spa',
    '2B': 'spa',
  },
  {
    '1': 'su',
    '2': 'sun',
    '3': 'sun',
    name: 'Sundanese',
    local: 'Basa Sunda',
    '2T': 'sun',
    '2B': 'sun',
  },
  {
    '1': 'sw',
    '2': 'swa',
    '3': 'swa',
    name: 'Swahili',
    local: 'Kiswahili',
    '2T': 'swa',
    '2B': 'swa',
  },
  {
    '1': 'ss',
    '2': 'ssw',
    '3': 'ssw',
    name: 'Swati',
    local: 'SiSwati',
    '2T': 'ssw',
    '2B': 'ssw',
  },
  {
    '1': 'sv',
    '2': 'swe',
    '3': 'swe',
    name: 'Swedish',
    local: 'Svenska',
    '2T': 'swe',
    '2B': 'swe',
  },
  {
    '1': 'ta',
    '2': 'tam',
    '3': 'tam',
    name: 'Tamil',
    local: 'தமிழ்',
    '2T': 'tam',
    '2B': 'tam',
  },
  {
    '1': 'te',
    '2': 'tel',
    '3': 'tel',
    name: 'Telugu',
    local: 'తెలుగు',
    '2T': 'tel',
    '2B': 'tel',
  },
  {
    '1': 'tg',
    '2': 'tgk',
    '3': 'tgk',
    name: 'Tajik',
    local: 'Тоҷикӣ',
    '2T': 'tgk',
    '2B': 'tgk',
  },
  {
    '1': 'th',
    '2': 'tha',
    '3': 'tha',
    name: 'Thai',
    local: 'ภาษาไทย',
    '2T': 'tha',
    '2B': 'tha',
  },
  {
    '1': 'ti',
    '2': 'tir',
    '3': 'tir',
    name: 'Tigrinya',
    local: 'ትግርኛ',
    '2T': 'tir',
    '2B': 'tir',
  },
  {
    '1': 'bo',
    '2': 'bod',
    '3': 'bod',
    name: 'Tibetan Standard',
    local: 'བོད་ཡིག',
    '2T': 'bod',
    '2B': 'tib',
  },
  {
    '1': 'tk',
    '2': 'tuk',
    '3': 'tuk',
    name: 'Turkmen',
    local: 'Türkmençe',
    '2T': 'tuk',
    '2B': 'tuk',
  },
  {
    '1': 'tl',
    '2': 'tgl',
    '3': 'tgl',
    name: 'Tagalog',
    local: 'Tagalog',
    '2T': 'tgl',
    '2B': 'tgl',
  },
  {
    '1': 'tn',
    '2': 'tsn',
    '3': 'tsn',
    name: 'Tswana',
    local: 'Setswana',
    '2T': 'tsn',
    '2B': 'tsn',
  },
  {
    '1': 'to',
    '2': 'ton',
    '3': 'ton',
    name: 'Tonga',
    local: 'faka Tonga',
    '2T': 'ton',
    '2B': 'ton',
  },
  {
    '1': 'tr',
    '2': 'tur',
    '3': 'tur',
    name: 'Turkish',
    local: 'Türkçe',
    '2T': 'tur',
    '2B': 'tur',
  },
  {
    '1': 'ts',
    '2': 'tso',
    '3': 'tso',
    name: 'Tsonga',
    local: 'Xitsonga',
    '2T': 'tso',
    '2B': 'tso',
  },
  {
    '1': 'tt',
    '2': 'tat',
    '3': 'tat',
    name: 'Tatar',
    local: 'Татарча',
    '2T': 'tat',
    '2B': 'tat',
  },
  {
    '1': 'tw',
    '2': 'twi',
    '3': 'twi',
    name: 'Twi',
    local: 'Twi',
    '2T': 'twi',
    '2B': 'twi',
  },
  {
    '1': 'ty',
    '2': 'tah',
    '3': 'tah',
    name: 'Tahitian',
    local: 'Reo Mā’ohi',
    '2T': 'tah',
    '2B': 'tah',
  },
  {
    '1': 'ug',
    '2': 'uig',
    '3': 'uig',
    name: 'Uyghur',
    local: 'ئۇيغۇرچه',
    '2T': 'uig',
    '2B': 'uig',
  },
  {
    '1': 'uk',
    '2': 'ukr',
    '3': 'ukr',
    name: 'Ukrainian',
    local: 'Українська',
    '2T': 'ukr',
    '2B': 'ukr',
  },
  {
    '1': 'ur',
    '2': 'urd',
    '3': 'urd',
    name: 'Urdu',
    local: 'اردو',
    '2T': 'urd',
    '2B': 'urd',
  },
  {
    '1': 'uz',
    '2': 'uzb',
    '3': 'uzb',
    name: 'Uzbek',
    local: 'O‘zbek',
    '2T': 'uzb',
    '2B': 'uzb',
  },
  {
    '1': 've',
    '2': 'ven',
    '3': 'ven',
    name: 'Venda',
    local: 'Tshivenḓa',
    '2T': 'ven',
    '2B': 'ven',
  },
  {
    '1': 'vi',
    '2': 'vie',
    '3': 'vie',
    name: 'Vietnamese',
    local: 'Tiếng Việt',
    '2T': 'vie',
    '2B': 'vie',
  },
  {
    '1': 'vo',
    '2': 'vol',
    '3': 'vol',
    name: 'Volapük',
    local: 'Volapük',
    '2T': 'vol',
    '2B': 'vol',
  },
  {
    '1': 'wa',
    '2': 'wln',
    '3': 'wln',
    name: 'Walloon',
    local: 'Walon',
    '2T': 'wln',
    '2B': 'wln',
  },
  {
    '1': 'cy',
    '2': 'cym',
    '3': 'cym',
    name: 'Welsh',
    local: 'Cymraeg',
    '2T': 'cym',
    '2B': 'wel',
  },
  {
    '1': 'wo',
    '2': 'wol',
    '3': 'wol',
    name: 'Wolof',
    local: 'Wolof',
    '2T': 'wol',
    '2B': 'wol',
  },
  {
    '1': 'fy',
    '2': 'fry',
    '3': 'fry',
    name: 'Western Frisian',
    local: 'Frysk',
    '2T': 'fry',
    '2B': 'fry',
  },
  {
    '1': 'xh',
    '2': 'xho',
    '3': 'xho',
    name: 'Xhosa',
    local: 'isiXhosa',
    '2T': 'xho',
    '2B': 'xho',
  },
  {
    '1': 'yi',
    '2': 'yid',
    '3': 'yid',
    name: 'Yiddish',
    local: 'ייִדיש',
    '2T': 'yid',
    '2B': 'yid',
  },
  {
    '1': 'yo',
    '2': 'yor',
    '3': 'yor',
    name: 'Yoruba',
    local: 'Yorùbá',
    '2T': 'yor',
    '2B': 'yor',
  },
  {
    '1': 'za',
    '2': 'zha',
    '3': 'zha',
    name: 'Zhuang',
    local: 'Cuengh',
    '2T': 'zha',
    '2B': 'zha',
  },
  {
    '1': 'zu',
    '2': 'zul',
    '3': 'zul',
    name: 'Zulu',
    local: 'isiZulu',
    '2T': 'zul',
    '2B': 'zul',
  },
];

export default allLanguages;
